### ISSUE TITLE
Buttons combo call home instead of startup

### ISSUE THREAD

**Issue by f0b04707** [tingbot/tbprocessd#3]
[tbbuttonsd.py](https://github.com/tingbot/tbprocessd/blob/master/tbbuttonsd.py#L25) `subprocess.call(['tbopen', '/apps/home'])` does not lunch the springboard, but the ​_ready_​ app. It should call the ​`/apps/startup`

**Comment by joerick** [comment]
In recent builds of the OS, both `/apps/home`  and `/apps/startup` point to the Springboard by default.

https://github.com/tingbot/tingbot-os/blob/master/root/apps/home

The intention is to allow the user to rewrite the `/apps/startup` to what the user would like when the Tingbot starts, but the /app/home will always point to an app launcher
