### ISSUE TITLE
Multiple instances of tbopen

### ISSUE THREAD

**Issue by f0b04707** [tingbot/tbprocessd#4]
As the time goes by, multiple instances of **tbopen** are opened and running in the background, wasting CPU time. Would be nice to have the home button combo function to kill current instance before calling a new one.

**Comment by joerick** [comment]
Is this when using Tide to remotely run apps on the Tingbot?

**Comment by f0b04707** [comment]
Both when they are run remotely from Tide only

**Comment by joerick** [comment]
The problem is likely that `tbopen --follow` doesn't exit at the end of the process like it should. It also doesn't output the log of the running process, so that's probably a related issue.
